### ISSUE TITLE
[ERROR] request#new (NoMethodError) "undefined method `to_unsafe_h' for #<ActiveSupport::HashWithIndifferentAccess:0x00007f87827873f8>

### ISSUE THREAD

**Issue by garethrees** [mysociety/askyourgovug-theme#26]
```
A NoMethodError occurred in request#new:

undefined method `to_unsafe_h' for #<ActiveSupport::HashWithIndifferentAccess:0x00007f87827873f8>
app/controllers/concerns/hashable_params.rb:10:in `params_to_unsafe_hash'

-------------------------------
Request:
-------------------------------

* URL : https://askyourgov.ug/new?post_redirect=1
* HTTP Method: GET
* Parameters : {"post_redirect"=>"1", "controller"=>"request", "action"=>"new"}
* Timestamp : 2020-08-20 14:26:50 +0300
* Rails root : /data/vhost/uganda.alaveteli.org/alaveteli-2020-08-19T16-22-31
* Process: 28219


-------------------------------
Backtrace:
-------------------------------

app/controllers/concerns/hashable_params.rb:10:in `params_to_unsafe_hash'
app/controllers/application_controller.rb:335:in `check_in_post_redirect'
lib/strip_empty_sessions.rb:15:in `call'
```

**Comment by garethrees** [comment]
Haven't seen any of these so probably just a case of old post redirects getting cleared
